# Generated by Django 2.1.2 on 2019-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='file',
            field=models.ImageField(default='user.png', null=True, upload_to='files/images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.ImageField(null=True, upload_to='files/'),
        ),
    ]
