# Generated by Django 2.1.2 on 2019-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_auto_20190324_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
