# Generated by Django 2.1.2 on 2019-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_auto_20190324_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='file',
            field=models.ImageField(default='/files/images/user.png', null=True, upload_to='files/images/'),
        ),
    ]
