# Generated by Django 2.1.2 on 2019-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_auto_20190324_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='file',
            field=models.ImageField(default='user.png', null=True, upload_to='files/images/'),
        ),
    ]
