# Generated by Django 2.1.2 on 2019-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_auto_20190324_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='file',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=14),
        ),
    ]
